#The Count Function

SELECT COUNT(*) FROM CITY
WHERE POPULATION>100000;

#The Sum Function

SELECT SUM(POPULATION) FROM CITY
WHERE DISTRICT="California";

#Averages

SELECT AVG(POPULATION) FROM CITY
WHERE DISTRICT="California";